### ISSUE TITLE
Kvasir ignores some simbols in ppt-list

### ISSUE THREAD

**Issue by vucinic** [codespecs/daikon#80] opened 2016-12-03 16:11 UTC
I'm working on Bzip2 example provided in Daikon package.

1. Given that local variables are not traced by Kvasir, I injected some dummy functions with empty bodies that simply takes variables as parameters (as suggested in Kvasir domunentation). One for each C scope in which variables are defined and a call to one of that functions for each C scope end.
2. Given that if all the Bzip2 functions are injected and then traced by Kvasir execution times becomes **very** long and Daikon systematically crashes with OutOfMemory exception (also with -Xmx4096m) I decided to limit the traced functions by using the `--dump-ppt-file `and `--ppt-list-file` (subsequently).

Then I observed the following behaviour: 
1. when I run Kvasir on the "injected" file without any limitation, namely without using `--ppt-list-file` option,  it discovers all the functions in the binary (original and injected ones);
2. when I selective trace the application by removing functions from the dumped ppt file and passing it to Kvasir (`--ppt-list-file`) it does not discover injected (empty) functions;
2.1. the same behaviour comes when I pass a ppt-file that contains all the functions collected by `--dump-ppt-file`.

In addition, strange but true, the `--dump-ppt-file` option is always able to collect all the function names (both injected and not).

Improvement: I tried to change the injected functions from "empty-bodied" to a "printf-containg" ones, nothing different.

Attached you can find the modified bzip2.c file (I added the .txt extension otherwise github prevents the load) and the ppt file containing all the function names.

[bzip2.c.txt](https://github.com/codespecs/daikon/files/628945/bzip2.c.txt)
[ppt-file.txt](https://github.com/codespecs/daikon/files/628946/ppt-file.txt)

**Comment by mernst** [comment] 2016-12-03 19:05
Thanks for getting in touch, and I'm sorry you are having trouble.
I'd like to help, but I couldn't tell from your message exactly what your issue is or what help you are seeking.

In particular, do you have an enhancement request?  If so what is it?

Or are you reporting a bug?  In that case, what are the exact commands that you executed, what did you expect to happen, and what happened erroneously instead?

**Comment by vucinic** [comment] 2016-12-04 17:53
I suppose it is a bug, but I cannot understand if I am doing something wrong.

If you have a look at the attached files you can see that I have injected some function to track local variables and, given that execution is very slow if I trace all the functions, I decided to use ppt-file to limit traced program points. The problem is that Kvasir does not trace the injected functions, even if I let untouched the ppt-file dumped by itself.

I am seeking a solution to this problem, either if I am doing something wrong or Kvasir has a bug.


Thanks.

**Comment by markro49** [comment] 2017-01-13 22:12
I could not reproduce your problem.  I compiled your version of bzip2 (with gcc -gdwarf-2 -o bz2n) and ran it on a very small input file to keep the running time short.  (I have attached my test input as s1.txt.) I used the following command line:
kvasir-dtrace --no-dyncomp  ./bz2n -z -k s1.txt
(note that --no-dyncomp is a very recent change; if you have not done a git pull in the last few days, you should omit this argument.) The file daikon-output/bz2n.dtrace contained ppts for all the injected functions.  I then ran with --dump-ppt-file=pptn to create a ppt file.  Finally,  I reran bz2n with:
 kvasir-dtrace --no-dyncomp --ppt-list-file=pptn ./bz2n -z -k s1.txt
The file  daikon-output/bz2n.dtrace was identical to the prior one.

Your could try getting the latest version of Daikon and repeating my experiment to see if you get the same results. 

[s1.txt](https://github.com/codespecs/daikon/files/705429/s1.txt)

**Comment by mernst** [comment] 2017-02-14 06:13
Not having heard a response to Mark's suggestion, I am going to close this issue.
If someone has more information, please supply it and re-open the issue.

**Closed by mernst** 2017-02-14 06:13 UTC
