### ISSUE TITLE
Instrumenting Junit

### ISSUE THREAD

**Issue by poosomooso** [codespecs/daikon#200] opened 2019-09-12 22:18 UTC
Hi, I'm trying to run Daikon on Junit tests. The tests run fine when I run them independently, but when I run them with Daikon, I get:

```
JUnit version 4.11
.E
Time: 0.033
There was 1 failure:
1) initializationError(op.OperationsTest)
java.lang.IllegalArgumentException: Test class can only have one constructor
	at org.junit.runners.model.TestClass.<init>(TestClass.java:40)
	at org.junit.runners.ParentRunner.<init>(ParentRunner.java:75)
	at org.junit.runners.BlockJUnit4ClassRunner.<init>(BlockJUnit4ClassRunner.java:57)
	at org.junit.internal.builders.JUnit4Builder.runnerForClass(JUnit4Builder.java:10)
	at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59)
	at org.junit.internal.builders.AllDefaultPossibilitiesBuilder.runnerForClass(AllDefaultPossibilitiesBuilder.java:26)
	at org.junit.runner.Computer.getRunner(Computer.java:40)
	at org.junit.runner.Computer$1.runnerForClass(Computer.java:31)
	at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59)
	at org.junit.runners.model.RunnerBuilder.runners(RunnerBuilder.java:101)
	at org.junit.runners.model.RunnerBuilder.runners(RunnerBuilder.java:87)
	at org.junit.runners.Suite.<init>(Suite.java:80)
	at org.junit.runner.Computer.getSuite(Computer.java:28)
	at org.junit.runner.Request.classes(Request.java:75)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:117)
	at org.junit.runner.JUnitCore.runMain(JUnitCore.java:96)
	at org.junit.runner.JUnitCore.runMainAndExit(JUnitCore.java:47)
	at org.junit.runner.JUnitCore.main(JUnitCore.java:40)

FAILURES!!!
Tests run: 1,  Failures: 1
```

Is this a problem with Daikon's instrumentation or am I missing something?

# Setup

Java: openjdk 1.8.0_222
OS: Ubuntu 18.04
Daikon: 5.7.4 (cloned from this repo) as well as 5.7.2 (downloaded from the website).

# Steps to replicate

```
git clone https://github.com/poosomooso/daikon-junit-test.git
cd daikon-junit-test
java -cp out/production/untitled:out/test/untitled:lib/*:$DAIKONDIR/daikon.jar daikon.DynComp org.junit.runner.JUnitCore op.OperationsTest
```

**Comment by mernst** [comment] 2020-06-08 22:37
I suspect the problem is that instrumentation doubles the constructor (creating a constructor that has an extra marker formal parameter), and JUnit craps out because JUnit expects a test case to have just one constructor.  Probably a special case is needed to handle constructors in JUnit test cases.

All of the above is just speculation; I have not yet investigated it.

**Comment by wilsondy** [comment] 2020-08-15 14:20
Interested in this - I can poke around if you point me where the constructor instrumentation happens.

**Comment by wilsondy** [comment] 2020-08-15 16:01
Ok - have done some recon but need guidance.
I desensitized jUnit to the two constructors and then it got very upset about having the test methods duplicated with the DCompMarker argument and the @org.junit.Test annotation.  I'm about an hour into Daikon land so I don't know which way to go.  Do I strip off the junit annotations somewhere in the instrumentation or have Daikon ignore the Test classes altogether?  (I don't care about invariants in the test case code).  See below an instrumented test class and the jUnit complaints.

![image](https://user-images.githubusercontent.com/2896543/90316239-e859bf80-deee-11ea-8545-c01eee4b7345.png)
![image](https://user-images.githubusercontent.com/2896543/90316253-fe678000-deee-11ea-8566-4d202667b5ac.png)

**Comment by markro49** [comment] 2020-08-15 18:59
There were two major problems for Java 11 we were stripping off the annotations and for all platforms we needed to special case JUnit test code to not duplicate most methods.  I am working on a pull request (https://github.com/codespecs/daikon/pull/271) to get JUnit tests working with DynComp.  Ran into a bit of trouble with Java 11, but I think I have that sorted out now.  Hope to finish the testing later this week.

**Comment by markro49** [comment] 2020-08-15 19:03
Forgot to mention that the current checked in code on the junit-support branch should work for Java 8.  Perhaps you could give it a  try?

**Comment by wilsondy** [comment] 2020-08-20 01:43
I have tried and it works better overall.  Unfortunately - I believe Testcases that extend other testcases may not work...

`junit.framework.AssertionFailedError: Exception in constructor: testCpioUnarchive (java.lang.NoSuchMethodError: org.apache.commons.compress.AbstractTestCase: method <init>(Ljava/lang/DCompMarker;)V not found
	at org.apache.commons.compress.archivers.CpioTestCase.<init>(CpioTestCase.java:33)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at junit.framework.TestSuite.createTest(TestSuite.java:59)
	at junit.framework.TestSuite.addTestMethod(TestSuite.java:296)
	at junit.framework.TestSuite.addTestsFromTestCase(TestSuite.java:139)
	at junit.framework.TestSuite.<init>(TestSuite.java:118)
	at org.junit.internal.runners.JUnit38ClassRunner.<init>(JUnit38ClassRunner.java:78)
	at org.junit.internal.builders.JUnit3Builder.runnerForClass(JUnit3Builder.java:11)
	at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:70)
	at org.junit.internal.builders.AllDefaultPossibilitiesBuilder.runnerForClass(AllDefaultPossibilitiesBuilder.java:37)
	at org.junit.runner.Computer.getRunner(Computer.java:50)
	at org.junit.runner.Computer$1.runnerForClass(Computer.java:31)
	at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:70)
	at org.junit.runners.model.RunnerBuilder.runners(RunnerBuilder.java:125)
	at org.junit.runners.model.RunnerBuilder.runners(RunnerBuilder.java:111)
	at org.junit.runners.Suite.<init>(Suite.java:81)
	at org.junit.runner.Computer$2.<init>(Computer.java:33)
	at org.junit.runner.Computer.getSuite(Computer.java:28)
	at org.junit.runner.Request.classes(Request.java:77)
	at org.junit.runner.JUnitCommandLineParseResult.createRequest(JUnitCommandLineParseResult.java:116)
	at org.junit.runner.JUnitCore.runMain(JUnitCore.java:77)
	at org.junit.runner.JUnitCore.main(JUnitCore.java:36)
)
`

**Comment by wilsondy** [comment] 2020-08-21 00:33
Different.  I'm taking a stroll through defects4j.  Here's a simple reproduction of the issue.

If you change the child test's parent to TestCase it works fine.  If not, it fails as above:
`junit.framework.AssertionFailedError: Exception in constructor: testHelloWorld (java.lang.NoSuchMethodError: com.company.ParentTest: method <init>(Ljava/lang/DCompMarker;)V not found


[example.tar.gz](https://github.com/codespecs/daikon/files/5106093/example.tar.gz)

**Comment by wilsondy** [comment] 2020-08-23 18:53
```
javac -cp junit-4.13.jar src/com/company/*.java
java -cp junit-4.13.jar:src:$DAIKONDIR/daikon.jar daikon.DynComp --ppt-omit-pattern=org.junit.*  org.junit.runner.JUnitCore com.company.ChildTest
```
My jUnit is a bit rusty, but if you extend TestCase it will reflect on the method names and run the public ones that have test in the name.
I also just tried adding the @Test annotation (and not extending TestCase) and the same behavior exists.  If you extend the ParentTest it dies iff ParentTest extends TestCase.

I've seen this test case parent class setup in two of the defects4j projects thus far:  commons-compress and closure-compiler, but I haven't made it very far into the other projects.

**Comment by mernst** [comment] 2020-08-23 20:16
Can you please provide the `src/com/company/*.java` files?
We need you to provide the exact commands you ran, and all of the files that they use, in order to reproduce your bug, fix it, and verify the fix.
Thanks.

**Comment by wilsondy** [comment] 2020-08-23 20:47
I gave the exact commands in my last comment and the source attached to the comment before that.  If you show me where to add this as a unit test I will even send a PR.

**Comment by markro49** [comment] 2020-08-23 22:19
i have reproduced the problem and am investigating.

**Comment by markro49** [comment] 2020-08-23 22:58
fixed - running regression tests

**Comment by wilsondy** [comment] 2020-08-24 00:44
Brilliant - thank you so much!

**Comment by markro49** [comment] 2020-08-24 18:13
Closing this issue.  If you have additional problems, please open a new issue.

**Closed by markro49** 2020-08-24 18:13 UTC
