### ISSUE TITLE
Crash: kvasir: fjalar_main.h:127 (fnStackTop): Assertion 'fn_stack_first_free_index[tid] >= 0' failed.

### ISSUE THREAD

**Issue by bingosxs** [codespecs/daikon#53] opened 2016-04-19 03:11 UTC
Hi, everyone.
I found a problem with daikon. The tests failed for a clean daikon from git.
They just crashed for the same reason.
This is one of the tests that failed. It seems that the code is not correctly initialized.

`$/daikon/tests/kvasir-tests/TypesTest$ /home/canicula/work/daikon-5.3.0/scripts/kvasir-dtrace  --decls-file=daikon-output/TypesTest.decls ./TypesTest  >TypesTest.out 2>&1`

**System information:**
```
daikon/tests/kvasir-tests/TypesTest$ uname -a
Linux  3.13.0-83-generic #127-Ubuntu SMP Fri Mar 11 00:26:47 UTC 2016 i686 i686 i686 GNU/Linux
/daikon/tests/kvasir-tests/TypesTest$ cat /etc/issue
Ubuntu 14.04.4 LTS \n \l
```

```
/daikon/tests/kvasir-tests/TypesTest$ gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/i686-linux-gnu/4.8/lto-wrapper
Target: i686-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 4.8.4-2ubuntu1~14.04.1' --with-bugurl=file:///usr/share/doc/gcc-4.8/README.Bugs --enable-languages=c,c++,java,go,d,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-4.8 --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --with-gxx-include-dir=/usr/include/c++/4.8 --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --enable-gnu-unique-object --disable-libmudflap --enable-plugin --with-system-zlib --disable-browser-plugin --enable-java-awt=gtk --enable-gtk-cairo --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-4.8-i386/jre --enable-java-home --with-jvm-root-dir=/usr/lib/jvm/java-1.5.0-gcj-4.8-i386 --with-jvm-jar-dir=/usr/lib/jvm-exports/java-1.5.0-gcj-4.8-i386 --with-arch-directory=i386 --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --enable-objc-gc --enable-targets=all --enable-multiarch --disable-werror --with-arch-32=i686 --with-multilib-list=m32,m64,mx32 --with-tune=generic --enable-checking=release --build=i686-linux-gnu --host=i686-linux-gnu --target=i686-linux-gnu
Thread model: posix
gcc version 4.8.4 (Ubuntu 4.8.4-2ubuntu1~14.04.1) 
```

**Error information:**

```
==29347== kvasir-5.3.0, C/C++ Language Front-End for Daikon with DynComp comparability analysis tool.
==29347== Copyright (C) 2007-2016, University of Washington CSE PLSE Group
==29347== Using Valgrind-3.11.0.Fjalar and LibVEX; rerun with -h for copyright info
==29347== Command: ./TypesTest
==29347== 

kvasir: fjalar_main.h:127 (fnStackTop): Assertion 'fn_stack_first_free_index[tid] >= 0' failed.

host stacktrace:
==29347==    at 0x380B0866: show_sched_status_wrk (m_libcassert.c:343)
==29347==    by 0x380B09A6: report_and_quit (m_libcassert.c:415)
==29347==    by 0x380B0ACB: vgPlain_assert_fail (m_libcassert.c:481)
==29347==    by 0x3800CB02: fnStackTop (fjalar_main.h:127)
==29347==    by 0x38011E3F: mc_new_mem_stack_4 (mc_main.c:3030)
==29347==    by 0x6478F038: ???

sched status:
  running_tid=1

Thread 1: status = VgTs_Runnable (lwpid 29347)
==29347==    at 0x40010D2: ??? (in /lib/i386-linux-gnu/ld-2.19.so)


Note: see also the FAQ in the source distribution.
It contains workarounds to several common problems.
In particular, if Valgrind aborted or crashed after
identifying problems in your program, there's a good chance
that fixing those problems will prevent Valgrind aborting or
crashing, especially if it happened in m_mallocfree.c.

If that doesn't help, please report this bug to: daikon-developers@googlegroups.com

In the bug report, send all the above text, the valgrind
version, and what OS and version you are using.  Thanks.

```

**Comment by markro49** [comment] 2016-04-19 16:03
duplicate of 32 bit issue #16

**Closed by markro49** 2016-04-19 16:03 UTC

**Comment by xinyik14** [comment] 2017-11-15 00:11
#16 Why are they the same? Sorry but I have the same problem and I don't know how to solve it by the answer of #16.

**Comment by markro49** [comment] 2017-11-15 01:02
Because I accidentally linked to Daikon issue 16 instead of Fjalar issue 16: https://github.com/codespecs/fjalar/issues/16
